tinyaes and folder restructuring
UWOrbital/CommsDemos pull request #8
Opened 2023-05-07 21:08 UTC by manumanuk

2023-05-08 19:59 UTC, christopherlam888 requested changes
Looks good.

2023-05-08 19:59 UTC, christopherlam888 commented on TinyAESEncryption/example.c
> +    AES_CTR_xcrypt_buffer(&decCtx, msg, 48);
Recommend adding comment indicating 48 is the length of the encrypted string.

2023-05-08 20:01 UTC, christopherlam888 approved these changes
Looks good.

2023-05-09 23:47 UTC, Navtajh04 approved these changes
LGTM

2023-05-13 03:08 UTC, merged